Use the given dataset, which consists of weather, temp and play as attributes. Perform the following task:

i. Apply data pre-processing and convert categorical values into numeric values.

ii. Use the list “weather”, “temp” as features and “play” as target. Try to create a model using Naïve bayes classifier to predict whether a person plays the game depending upon the values of weather and temperature.
  
weather=['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny','Sunny','Rainy','Sunny','Overcast','Overcast','Rainy']

temp=['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']

play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']



In [17]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

In [18]:
weather=['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny','Sunny','Rainy','Sunny',
         'Overcast','Overcast','Rainy']
temp=['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']

play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']

In [19]:
le=LabelEncoder()
weather=le.fit_transform(weather)
weather

array([2, 2, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1])

In [20]:
temp=le.fit_transform(temp)
temp

array([1, 1, 1, 2, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2])

In [21]:
target=le.fit_transform(play)
target

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [29]:
data=list(zip(weather,temp))
features_df=pd.DataFrame(data,columns=['weather','temp'])

In [30]:
features_df

weather  temp
0         2     1
1         2     1
2         0     1
3         1     2
4         1     0
5         1     0
6         0     0
7         2     2
8         2     0
9         1     2
10        2     2
11        0     2
12        0     1
13        1     2

In [24]:
gn=GaussianNB()
model=gn.fit(features_df,target)

In [35]:
x_test=np.array([[1,1],[2,1],[2,0],[1,2],[0,1]])
y_test=np.array([1,0,1,1,1])

In [36]:
y_pred=model.predict(x_test)

In [38]:
print( "Accuracy is ", accuracy_score(y_test,y_pred)*100)

Accuracy is  80.0
